import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author INFINIX
 */
public class Soal2 extends javax.swing.JFrame {

    /**
     * Creates new form Warung
     */
    public Soal2() {
        initComponents();
        tfJumlah.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbJumlahBeli = new javax.swing.JLabel();
        btPlus = new javax.swing.JButton();
        btMin = new javax.swing.JButton();
        tfJumlah = new javax.swing.JTextField();
        btBeli = new javax.swing.JButton();
        btHapus = new javax.swing.JButton();
        lbInfoPesanan = new javax.swing.JLabel();
        lbPesanan = new javax.swing.JLabel();
        lbHarga = new javax.swing.JLabel();
        lbJumlahPesanan = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        tfPesanan = new javax.swing.JTextField();
        tfHarga = new javax.swing.JTextField();
        tfJumlahPesan = new javax.swing.JTextField();
        tfTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        AyamGeprek = new javax.swing.JRadioButton();
        Soto = new javax.swing.JRadioButton();
        Bakso = new javax.swing.JRadioButton();
        Rujak = new javax.swing.JRadioButton();
        Nascam = new javax.swing.JRadioButton();
        Nasgor = new javax.swing.JRadioButton();
        Miepan = new javax.swing.JRadioButton();
        Capcay = new javax.swing.JRadioButton();
        Ikbar = new javax.swing.JRadioButton();
        Gado = new javax.swing.JRadioButton();
        lbBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lbJumlahBeli.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        lbJumlahBeli.setText("Jumlah Beli");

        btPlus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btPlus.setText("+");
        btPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPlusActionPerformed(evt);
            }
        });

        btMin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btMin.setText("-");
        btMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMinActionPerformed(evt);
            }
        });

        tfJumlah.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJumlahActionPerformed(evt);
            }
        });

        btBeli.setText("Beli");
        btBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBeliActionPerformed(evt);
            }
        });

        btHapus.setText("Hapus");
        btHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHapusActionPerformed(evt);
            }
        });

        lbInfoPesanan.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        lbInfoPesanan.setText("Informasi Pesanan");

        lbPesanan.setText("Pesananan Anda  :");

        lbHarga.setText("Harga                   :");

        lbJumlahPesanan.setText("Jumlah Pesanan   :");

        lbTotal.setText("Total                    :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbPesanan)
                        .addGap(21, 21, 21)
                        .addComponent(tfPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbHarga)
                        .addGap(18, 18, 18)
                        .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbJumlahPesanan)
                            .addComponent(lbTotal))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(tfJumlahPesan)))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btBeli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btHapus)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btPlus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btMin)
                                .addGap(12, 12, 12))
                            .addComponent(tfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbJumlahBeli, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbInfoPesanan)
                        .addGap(73, 73, 73))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbJumlahBeli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPlus)
                    .addComponent(btMin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBeli)
                    .addComponent(btHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbInfoPesanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPesanan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbJumlahPesanan)
                    .addComponent(tfJumlahPesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTotal)
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 300, 330));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setText("WAROENG ANAK PANAH");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        Menu.add(AyamGeprek);
        AyamGeprek.setText("Ayam Geprek");
        AyamGeprek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyamGeprekActionPerformed(evt);
            }
        });
        getContentPane().add(AyamGeprek, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        Menu.add(Soto);
        Soto.setText("Soto");
        getContentPane().add(Soto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        Menu.add(Bakso);
        Bakso.setText("Bakso");
        getContentPane().add(Bakso, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        Menu.add(Rujak);
        Rujak.setText("Rujak");
        getContentPane().add(Rujak, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        Menu.add(Nascam);
        Nascam.setText("Nasi Campur");
        getContentPane().add(Nascam, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        Menu.add(Nasgor);
        Nasgor.setText("Nasi Goreng");
        getContentPane().add(Nasgor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        Menu.add(Miepan);
        Miepan.setText("Mie Pangsit");
        getContentPane().add(Miepan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        Menu.add(Capcay);
        Capcay.setText("Capcay");
        getContentPane().add(Capcay, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        Menu.add(Ikbar);
        Ikbar.setText("Ikan Bakar");
        getContentPane().add(Ikbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        Menu.add(Gado);
        Gado.setText("Gado Gado");
        getContentPane().add(Gado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        lbBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        getContentPane().add(lbBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AyamGeprekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyamGeprekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AyamGeprekActionPerformed

    private void tfJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJumlahActionPerformed

    private void btPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPlusActionPerformed
        // TODO add your handling code here:
        int jumlah = Integer.parseInt(tfJumlah.getText());
            jumlah++;
            tfJumlah.setText(Integer.toString(jumlah));
    }//GEN-LAST:event_btPlusActionPerformed

    private void btMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMinActionPerformed
        // TODO add your handling code here:
        int jumlah = Integer.parseInt(tfJumlah.getText());
        if (jumlah > 0) {
            jumlah--;
            tfJumlah.setText(Integer.toString(jumlah));
        }
    }//GEN-LAST:event_btMinActionPerformed

    private void btBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBeliActionPerformed
        // TODO add your handling code here:
        String pesanan = "";
        int harga = 0;

        if (AyamGeprek.isSelected()) {
            pesanan = "Ayam Geprek";
            harga = 9000;
        } else if (Soto.isSelected()) {
            pesanan = "Soto";
            harga = 8000;
        }else if (Bakso.isSelected()) {
            pesanan = "Bakso";
            harga = 10000;
        }else if (Rujak.isSelected()) {
            pesanan = "Rujak";
            harga = 10000;
        }else if (Nascam.isSelected()) {
            pesanan = "Nasi Campur";
            harga = 13000;
        }else if (Nasgor.isSelected()) {
            pesanan = "Nasi Goreng";
            harga = 10000;
        }else if (Miepan.isSelected()) {
            pesanan = "Mie Pangsit";
            harga = 10000;
        }else if (Capcay.isSelected()) {
            pesanan = "Capcay";
            harga = 11000;
        }else if (Ikbar.isSelected()) {
            pesanan = "Ikan Bakar";
            harga = 20000;
        }else if (Gado.isSelected()) {
            pesanan = "Gado Gado";
            harga = 10000;
        }
        
        int jumlah = Integer.parseInt(tfJumlah.getText());

        int totalHarga = harga * jumlah;
        tfTotal.setText("Rp" + totalHarga);
  
        if (pesanan != null && jumlah > 0) {
            tfPesanan.setText(pesanan);
            tfHarga.setText("Rp" + Integer.toString(harga));
            tfJumlahPesan.setText(Integer.toString(jumlah));
        } else {
            JOptionPane.showMessageDialog(null, "Pilih menu dan pastikan jumlah beli lebih dari 0.",
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btBeliActionPerformed

    private void btHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapusActionPerformed
        // TODO add your handling code here:
        Menu.clearSelection();
        tfJumlah.setText("0");
        tfPesanan.setText("");
        tfJumlahPesan.setText("");
        tfTotal.setText("");
        tfHarga.setText("");
    }//GEN-LAST:event_btHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AyamGeprek;
    private javax.swing.JRadioButton Bakso;
    private javax.swing.JRadioButton Capcay;
    private javax.swing.JRadioButton Gado;
    private javax.swing.JRadioButton Ikbar;
    private javax.swing.ButtonGroup Menu;
    private javax.swing.JRadioButton Miepan;
    private javax.swing.JRadioButton Nascam;
    private javax.swing.JRadioButton Nasgor;
    private javax.swing.JRadioButton Rujak;
    private javax.swing.JRadioButton Soto;
    private javax.swing.JButton btBeli;
    private javax.swing.JButton btHapus;
    private javax.swing.JButton btMin;
    private javax.swing.JButton btPlus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBg;
    private javax.swing.JLabel lbHarga;
    private javax.swing.JLabel lbInfoPesanan;
    private javax.swing.JLabel lbJumlahBeli;
    private javax.swing.JLabel lbJumlahPesanan;
    private javax.swing.JLabel lbPesanan;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfJumlah;
    private javax.swing.JTextField tfJumlahPesan;
    private javax.swing.JTextField tfPesanan;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables
}
